#!/usr/bin/env bash
# -*- coding: utf-8 -*-
set -euo pipefail

# ========================================
# Codex 設定同期スクリプト
# ========================================
#
# 前提: UTF-8 ロケール（ja_JP.UTF-8, en_US.UTF-8 など）
# 文字化けする場合: export LANG=ja_JP.UTF-8 または export LANG=en_US.UTF-8
# ========================================
#
# 目的:
#   共有設定ファイル（config.shared.toml）の内容を
#   ローカル設定ファイル（~/.codex/config.toml）に同期しつつ、
#   Codex が自動生成する [projects."..."] セクションと
#   ローカル端末依存の [windows] セクションを保持する
#
# 使い方:
#   sync-codex-config
#   または
#   sync-codex-config <共有設定パス> <ターゲット設定パス>
# ========================================

# シンボリックリンク経由で実行された場合でも、
# 実際のスクリプトの場所を正しく解決する
SOURCE="${BASH_SOURCE[0]}"
while [[ -h "${SOURCE}" ]]; do
  DIR="$(cd -P "$(dirname "${SOURCE}")" && pwd)"
  LINK_TARGET="$(readlink "${SOURCE}")"
  if [[ "${LINK_TARGET}" == /* ]]; then
    SOURCE="${LINK_TARGET}"
  else
    SOURCE="${DIR}/${LINK_TARGET}"
  fi
done

# スクリプトのディレクトリとリポジトリルートを特定
SCRIPT_DIR="$(cd -P "$(dirname "${SOURCE}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# 引数で指定されていない場合はデフォルトパスを使用
SHARED_CONFIG="${1:-${REPO_ROOT}/.codex/config.shared.toml}"
TARGET_CONFIG="${2:-${HOME}/.codex/config.toml}"

# 共有設定ファイルの存在確認
if [[ ! -f "${SHARED_CONFIG}" ]]; then
  echo "[sync-codex-config] エラー: 共有設定ファイルが見つかりません: ${SHARED_CONFIG}" >&2
  echo "まず ${SHARED_CONFIG} を作成してください（[projects.\"...\"] セクションは含めないでください）。" >&2
  exit 1
fi

# 共有設定ファイルに [projects."..."] セクションが含まれていないか確認
# （これらは Codex が自動生成するため、共有設定には含めない）
if grep -Eq "^\[projects\.(\"|')" "${SHARED_CONFIG}"; then
  echo "[sync-codex-config] エラー: 共有設定ファイルに [projects.\"...\"] セクションを含めることはできません: ${SHARED_CONFIG}" >&2
  exit 1
fi

# 共有設定ファイルに [windows] セクションが含まれていないか確認
# （これはローカル端末依存のため、共有設定には含めない）
if grep -Eq "^[[:space:]]*\[windows\][[:space:]]*$" "${SHARED_CONFIG}"; then
  echo "[sync-codex-config] エラー: 共有設定ファイルに [windows] セクションを含めることはできません: ${SHARED_CONFIG}" >&2
  exit 1
fi

shared_config_has_top_level_notify() {
  local python_cmd

  for python_cmd in python3 python; do
    if command -v "${python_cmd}" >/dev/null 2>&1; then
      "${python_cmd}" - "${SHARED_CONFIG}" <<'PY'
import pathlib
import sys

path = pathlib.Path(sys.argv[1])
text = path.read_text(encoding="utf-8")

try:
    import tomllib  # Python 3.11+
    data = tomllib.loads(text)
except ModuleNotFoundError:
    try:
        import toml
    except ModuleNotFoundError:
        print("[sync-codex-config] エラー: Python の TOML パーサーが見つかりません。python3.11+ または toml パッケージが必要です", file=sys.stderr)
        sys.exit(2)
    data = toml.loads(text)
except Exception as exc:
    print(f"[sync-codex-config] エラー: 共有設定ファイルの TOML 解析に失敗しました: {path}", file=sys.stderr)
    print(str(exc), file=sys.stderr)
    sys.exit(2)

sys.exit(0 if "notify" in data else 1)
PY
      return $?
    fi
  done

  echo "[sync-codex-config] エラー: top-level notify の検査に Python が必要です" >&2
  exit 1
}

# 共有設定ファイルに top-level の notify キーが含まれていないか確認
# （notify は環境依存のため、このスクリプトが machine-local に注入する）
notify_check_result=0
if shared_config_has_top_level_notify; then
  notify_check_result=0
else
  notify_check_result=$?
fi

if [[ ${notify_check_result} -eq 2 ]]; then
  exit 1
fi

if [[ ${notify_check_result} -eq 0 ]]; then
  echo "[sync-codex-config] エラー: 共有設定ファイルに notify を含めることはできません: ${SHARED_CONFIG}" >&2
  echo "[sync-codex-config] notify は環境依存値のため、このスクリプトが machine-local 設定として注入します" >&2
  exit 1
fi

# ターゲット設定ファイルのディレクトリを作成（存在しない場合）
mkdir -p "$(dirname "${TARGET_CONFIG}")"

# 一時ファイルを作成
tmp_target="$(mktemp "${TARGET_CONFIG}.tmp.XXXXXX")"
tmp_preserved="$(mktemp "${TARGET_CONFIG}.preserved.XXXXXX")"

# スクリプト終了時に一時ファイルを削除
cleanup() {
  rm -f "${tmp_target}" "${tmp_preserved}"
}
trap cleanup EXIT

toml_basic_escape() {
  local value
  value="$1"
  value=${value//\\/\\\\}
  value=${value//\"/\\\"}
  value=${value//$'\t'/\\t}
  value=${value//$'\r'/\\r}
  value=${value//$'\n'/\\n}
  printf "%s" "${value}"
}

append_machine_local_notify_config() {
  local os_type notify_program notify_target

  os_type="$(uname -s)"
  case "${os_type}" in
    MINGW* | MSYS* | CYGWIN*)
      notify_program="wscript.exe"
      if ! command -v cygpath >/dev/null 2>&1; then
        echo "[sync-codex-config] エラー: Windows では cygpath が必要です。Git Bash / MSYS から再実行してください" >&2
        exit 1
      fi
      notify_target="$(cygpath -w "${REPO_ROOT}/.agent/notification/notify.js")"
      ;;
    *)
      notify_program="sh"
      notify_target="${REPO_ROOT}/.agent/notification/notify.sh"
      ;;
  esac

  {
    printf "# Machine-local notification command generated by sync-codex-config.sh\n"
    printf "# Absolute paths are injected here because Codex notify uses argv tokens directly.\n"
    printf 'notify = ["%s", "%s"]\n\n' \
      "$(toml_basic_escape "${notify_program}")" \
      "$(toml_basic_escape "${notify_target}")"
  } >> "${tmp_target}"
}

# 既存のターゲット設定ファイルから machine-local セクションのみを抽出
# - [projects."..."] / [projects.'...'] は Codex が自動生成するため保持する
# - [windows] はローカル端末依存のため保持する
if [[ -f "${TARGET_CONFIG}" ]]; then
  awk '
    BEGIN { in_preserved = 0 }

    /^[[:space:]]*\[projects\.(["][^"]+["]|'\''[^'\'']+'\'')\][[:space:]]*$/ {
      in_preserved = 1
      print
      next
    }

    /^[[:space:]]*\[windows\][[:space:]]*$/ {
      in_preserved = 1
      print
      next
    }

    /^[[:space:]]*\[/ {
      in_preserved = 0
    }

    in_preserved {
      print
    }
  ' "${TARGET_CONFIG}" > "${tmp_preserved}"
fi

# machine-local notify を最初に書き出し、その後に共有設定を追記する
# こうすることで notify が常にトップレベルに配置される
append_machine_local_notify_config
cat "${SHARED_CONFIG}" >> "${tmp_target}"

# 抽出した machine-local セクションがあれば、一時ファイルに追記
if [[ -s "${tmp_preserved}" ]]; then
  printf "\n" >> "${tmp_target}"
  cat "${tmp_preserved}" >> "${tmp_target}"
fi

# 一時ファイルでターゲット設定ファイルを置き換え
mv "${tmp_target}" "${TARGET_CONFIG}"

# 同期完了メッセージ
echo "[sync-codex-config] ${SHARED_CONFIG} から ${TARGET_CONFIG} に同期しました"
if [[ -s "${tmp_preserved}" ]]; then
  project_count="$(grep -Ec '^\[projects\.' "${tmp_preserved}" || true)"
  echo "[sync-codex-config] ${project_count} 個のプロジェクトセクションを保持しました"
else
  echo "[sync-codex-config] 保持するプロジェクトセクションはありませんでした"
fi

if rg -q '^\[windows\]$' "${tmp_preserved}" 2>/dev/null; then
  echo "[sync-codex-config] [windows] セクションを保持しました"
fi

echo "[sync-codex-config] Machine-local notify command を設定しました"
